# Generated by Django 3.2.12 on 2022-03-03 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.pastebin.models.validator
import project.pastebin.utils.file_save


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('text_file', models.FileField(blank=True, null=True, upload_to=project.pastebin.utils.file_save.PathAndRename('pastes/files/'), validators=[project.pastebin.models.validator.validate_file_extension])),
                ('name', models.CharField(blank=True, max_length=5, null=True)),
                ('slug', models.CharField(blank=True, max_length=8, null=True)),
                ('accessed', models.PositiveIntegerField(default=0)),
                ('destroyable', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
