# Generated by Django 3.2.12 on 2022-03-04 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastes', to=settings.AUTH_USER_MODEL),
        ),
    ]
