# Generated by Django 3.2.12 on 2022-03-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_alter_user_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
    ]
